### ISSUE TITLE
How to remove token?

### ISSUE THREAD

**Issue by bdube** [nanos/GetAuth#1]
Hello,

Thanks for making this. It's working for me right now.

After creating the token, I don't see any applications listed for an admin user or the non-admin user the token was generated for. If the grant needs to be removed, how is this done?

Thank you.

**Comment by nanos** [comment]
These aren’t admin tokens, which is why they aren’t listed in the admin section.

These are app tokens and are therefore listed with the other app tokens at Account > Authorised Apps.

**Comment by bdube** [comment]
Sorry, I see it now. Thanks.
